spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:

server:
  servlet:
    session:
      timeout:
  error:
    whitelabel:
      enabled: false

  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 100


git:
  gitId:
  gitToken:
  imgUrl:
  repo:
  imgRepo:


---
spring:
  profiles:
    active: dev
