spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:

server:
  servlet:
    session:
      timeout:
  error:
    whitelabel:
      enabled: false

git:
  gitId:
  gitToken:
  imgUrl:
  repo:
  imgRepo:


---
spring:
  profiles:
    active: dev
